/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

package main

import "fmt"

func main() {

	var a = 1
	var b = 1
	var c = a + b
	var sum = 0

	for true {
		if (c < 4000000) && (c % 2 == 0){
			sum = sum + c 
		}
		if (c > 4000000){
			break
		}
		a = b
		b = c 
		c = a + b 
	}
	fmt.Printf("%d", sum)
}